### ISSUE TITLE
 Error returned, discarding txhashset extension: Other Error: output vs rproof MMRs different sizes

### ISSUE THREAD

**Issue by teknowill** [mimblewimble/docs#13]
I can't get the node to start

rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)

uname -r
4.15.0-39-generic

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

cat ~/grin/grin-server.log

20190119 21:23:22.983 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20190119 21:23:22.983 INFO grin - Using configuration file at /home/wpatino/grin/grin-server.toml
20190119 21:23:22.983 INFO grin - This is Grin version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
20190119 21:23:22.983 DEBUG grin - Built with profile "release", features "".
20190119 21:23:22.983 WARN grin::cmd::server - Starting GRIN in UI mode...
20190119 21:23:22.984 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190119 21:23:23.029 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Other Error: output vs rproof MMRs different sizes
 Cause: Unknown
 Backtrace:
20190119 21:23:23.056 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': libcore/result.rs:1009stack backtrace:
   0:     0x55d03677879d - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x55d0367779b2 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x55d036777a29 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x55d036701630 - grin_util::logger::send_panic_to_log::{{closure}}::h6b81febaf2dee014
   4:     0x55d036849226 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55d036848d71 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55d036848c55 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55d036892ccc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55d035fd2419 - core::result::unwrap_failed::h830a8bfc4a83e400
   9:     0x55d035f6e3b0 - grin::cmd::server::start_server::h865872809e516a65
  10:     0x55d035f6f068 - grin::cmd::server::server_command::hc789d325932205ed
  11:     0x55d035ffe9fc - grin::real_main::h7464ec6aee075aa9
  12:     0x55d035ffcee5 - grin::main::h76cf7ec850a9936e
  13:     0x55d035fcb1d2 - std::rt::lang_start::{{closure}}::hd67b3eb73f2382c8
  14:     0x55d036848bf2 - std::rt::lang_start_internal::{{closure}}::hafa8ecdacd368ebb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8c0dbb48abbdf4df
                        at libstd/panicking.rs:310
  15:     0x55d03685b2c9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  16:     0x55d03682a44a - std::panicking::try::hbc21637ba5f64d73
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h954917b922b8d970
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h5b2de3cc38c3b406
                        at libstd/rt.rs:58
  17:     0x55d035fff364 - main
  18:     0x7f96e773db96 - __libc_start_main
  19:     0x55d035f41980 - <unknown>
  20:                0x0 - <unknown>

**Comment by teknowill** [comment]
the acsii menu never starts. 

so I just did
grin server config
grin-server.toml file configured and created in current directory

grin
Illegal instruction (core dumped)

and then you get the above. if you delete the chain_data folder it just repeats core dump and then on next run you get what's in the log

**Comment by sesam** [comment]
Hi @teknowill ! This issue is in the wrong github - could you please close it? The best place for help building and running grin is start at the [troubleshooting page](https://github.com/mimblewimble/docs/wiki/Troubleshooting) and then come to the support chat: https://gitter.im/grin_community/support
