### ISSUE TITLE
cannot create directory file exists

### ISSUE THREAD

**Issue by rw258906** [mimblewimble/docs#16]
When typing mkdir ~/grin it doesn't let you make the directory since the previous command creates a file named grin and Ubuntu will not let you have a file and a folder with the same name in the same directory.

**Comment by sesam** [comment]
which doc url has mkdir, if you've still got it handy to paste? it is
outdated info.

**Comment by rw258906** [comment]
it's under installation, linux (all distros) from: [https://github.com/mimblewimble/docs/wiki/how-to-run-a-grin-node#linux-all-distributions](https://github.com/mimblewimble/docs/wiki/how-to-run-a-grin-node#linux-all-distributions)

tar xzf grin-v1.0.0-479973573-linux-amd64.tgz
mkdir ~/grin
cp grin ~/grin
echo export 'PATH=~/grin:$PATH' >> ~/.bashrc
source ~/.bashrc
