### ISSUE TITLE
"How to: Run a Grin node on Google Cloud for free" docs are outdated

### ISSUE THREAD

**Issue by liamaharon** [mimblewimble/docs#21]
Some of the things that need updating:
- remove references to `grin.toml`, instead add instructions to create a `grin-wallet.toml`, explain how access & modify it via the `~/.grin` dir
- update for mainnet (port number, etc)
- mention when the user should do something different if they want to connect to floonet

If this sounds OK let me know and I'll open a PR

**Comment by sesam** [comment]
Seems fine. If you didn't yet start editing, maybe make it in pieces, starting with correcting port numbera and file names. Get that merged.
Because then the next part about better explaining will probably get some interest and request for changes before merge.

**Comment by Lalit15** [comment]
Yes I am facing issue while trying to setup a node on Google cloud using the steps mentioned in the doc.
Specially part related to moving grin.toml from target to release as their is no grin.toml created in the grin folder.

Also, I am not start a grin wallet using command grin wallet init as there is error saying incorrect command. Kindly mention steps in detail on how to setup wallet on cloud and sync wallet with grin node  on cloud.

**Comment by lehnberg** [comment]
If you are referring to: https://github.com/mimblewimble/docs/wiki/How-to%3A-Run-a-Grin-node-on-Google-Cloud-for-free

I just want to make you aware that this is a wiki article and does not require issues nor pull requests. Feel free to make corrections directly by pressing "Edit" in the upper right hand corner. :)

**Comment by liamaharon** [comment]
Sorry, I haven't forgotten about this. Will find time in the next 24hrs to make the updates. 

Thanks @lehnberg @sesam for letting me know a PR is not necessary, I'll use the "edit" button as you suggest

**Comment by liamaharon** [comment]
Doc have been updated. 

Feel free to suggest/make further improvements, otherwise I think this issue can be closed :)

**Comment by Lalit15** [comment]
@liamaharon - Thanks mate for updating the doc...have been able to successfully setup following the steps mentioned in the document
