### ISSUE TITLE
Can't install grin node

### ISSUE THREAD

**Issue by vasilevskykv** [mimblewimble/docs#22]
I try to install grin node, using
grin -v1.0.1-487947758-linux-amd64.tgz
I get a message:
tar: Options '-[0-7][lmh]' not supported by *this* tar
What should I install?
My GPU is Nvidia GTX 1070.

**Comment by pluksitmania** [comment]
I try to install grin node, using
grin -v1.0.1-487947758-linux-amd64.tgz
I get a message:
tar: Options '-[0-7][lmh]' not supported by this tar
What should I install?
My GPU is Nvidia GTX 1070.

**Comment by ignopeverell** [comment]
This has nothing to do with grin and everything with you decompressing an archive. Github isn't the right place for support, please try https://gitter.im/grin_community/support
