### ISSUE TITLE
Coalesce "Contributing" docs

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/docs#3]
https://github.com/mimblewimble/docs/wiki/Hacking-and-contributing
https://github.com/mimblewimble/grin/blob/master/CONTRIBUTING.md

Merging these docs into a single one would be beneficial to keep the instructions up to date and in a single place for better maintainance. The R&D "Hacking and contributing" section in the wiki can point directly to CONTRIBUTING.md in mimblewimble/grin as it's probably desirable to keep the latter.

**Comment by garyyu** [comment]
@kargakis  Could you merge it and submit PR to Grin repo? 😄   then you can delete https://github.com/mimblewimble/docs/wiki/Hacking-and-contributing and put simple link only.
