### ISSUE TITLE
[WIP] Suggestions to improve the DOCS

### ISSUE THREAD

**Issue by WarmBeer** [mimblewimble/docs#35]
**Changes**
- In Quickstart/Install/Linux "Replace $VESION with..." - Should be $VERSION
- [Windows only] in Quickstart/Install/Windows change ```set PATH=%PATH%;C:\Users\%USER%\AppData\Local``` to ```set PATH=%PATH%;C:\Users\%USER%\AppData\Local\Grin``` OR ```set PATH=%PATH%;$PATH_TO_FOLDER_CONTAINING_GRIN_BINARIES```

**Additions**
- Explain how to install ToR prior to showing the command ```grin-wallet listen```
- [Linux only] in Quickstart/Install/Linux show how to download the tar.gz files using just the CLI
eg:
```
wget https://github.com/mimblewimble/grin/releases/latest/download/grin-$VERSION-linux-amd64.tar.gz
wget https://github.com/mimblewimble/grin-wallet/releases/latest/download/grin-wallet-$VERSION-linux-amd64.tar.gz
```
- [Windows only] in Quickstart/Install/Windows tell users to install Microsoft Visual C++ 2015 from https://www.microsoft.com/en-us/download/details.aspx?id=52685 (Grin won't work without it)

**Comment by Paouky** [comment]
Huh for some reason I only noticed this now. Noted.

**Comment by Paouky** [comment]
[PR#53](https://github.com/mimblewimble/docs/pull/53)

**Comment by Paouky** [comment]
[PR#53](https://github.com/mimblewimble/docs/pull/53)
