### ISSUE TITLE
CSS Issue on hyperlinkgs

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/docs#61]
See these screen caps:
<img width="476" alt="Capture d’écran 2021-04-07 à 10 31 02" src="https://user-images.githubusercontent.com/11842328/113883775-75a69880-978c-11eb-97e5-b9ede9ba8345.png">
On hover:
<img width="476" alt="Capture d’écran 2021-04-07 à 10 31 04" src="https://user-images.githubusercontent.com/11842328/113883792-79d2b600-978c-11eb-8059-9926e94c9178.png">

**Comment by quentinlesceller** [comment]
it's actually the same on desktop
![Capture d’écran 2021-04-07 à 10 34 21](https://user-images.githubusercontent.com/11842328/113884299-db932000-978c-11eb-9b25-abf873700478.png)

**Comment by quentinlesceller** [comment]
![Uploading Capture d’écran 2021-04-07 à 10.35.16.png…]()

**Comment by raballew** [comment]
@quentinlesceller Might be already fixed in https://github.com/mimblewimble/docs/pull/59. Not sure about the hover icon and color though.

**Comment by quentinlesceller** [comment]
I think this was fixed a long time ago. Closing.
